"""Umformulierungen für Records, bei denen die Wertevariation nichts bewirkt.

52 der 151 Basis-Records enthalten keinen austauschbaren Wert -- "beende die anwendung"
-> close_application -> "Die Anwendung wird geschlossen." hat weder Engine-Namen noch
Pfad noch Zahl. Die drei Welten aus variants.py liefern dort dreimal exakt dasselbe, also
106 tote Kopien. Für ein SFT ist das kein neutraler Füller, sondern ein versehentliches
Gewicht: bei 3 Epochen sieht das Modell so ein Beispiel 9-mal statt 3-mal und lernt eher
die Zeichenkette als die Regel.

Statt sie wegzuwerfen, bekommt jedes dieser Records je Welt eine eigene Formulierung --
in User-Nachricht UND Antwort. Damit wird aus totem Gewicht das, was diesen Tools
tatsächlich fehlt: Vielfalt in der Zuordnung Intent -> Tool und in der Antwortform.

Regeln beim Umformulieren:
  * Der Tool-Aufruf bleibt identisch -- variiert wird nur, wie gefragt und geantwortet wird.
  * Die Antwort bleibt gedeckt: keine Zahl, kein Name, kein Pfad, der nicht schon im
    Tool-Ergebnis desselben Records steht. verify.py prüft das.
  * Register wie in den echten Sitzungen: klein geschrieben, direkt, Tippfehler erlaubt.
  * Die Antwort bleibt kurz. Länge ist die Fläche, auf der halluziniert wird.

Reihenfolge je Record entspricht WORLDS in variants.py.
"""

# index -> [(user, reply) für Welt 1, (user, reply) für Welt 2]
# reply=None bei Records, die auf einem terminalen Tool enden.
PARAPHRASES = {
    2: [("starte das turnier bitte", "Das Turnier ist gestartet."),
        ("los, turnier starten", "Läuft.")],
    6: [("wie viele partien fehlen noch?", "Der Stand steht als Tabelle im Chat."),
        ("wieviel ist noch offen im turnier?", "Die Tabelle im Chat zeigt den Stand.")],
    7: [("was läuft im moment?", "Es läuft ein klassisches Turnier, sonst nichts."),
        ("laufen gerade irgendwelche tests?",
         "Nur ein klassisches Turnier. SPRT und EPD sind nicht aktiv.")],
    10: [("was läuft grad?", "Turnier und SPRT-Test laufen parallel, keine EPD-Analyse."),
         ("sag mir was aktuell läuft",
          "Es laufen ein Turnier und ein SPRT-Test. Eine EPD-Analyse nicht.")],
    12: [("und was läuft jetzt?", "Turnier und SPRT-Test laufen, EPD nicht."),
         ("was ist gerade aktiv?",
          "Aktiv sind ein klassisches Turnier und ein SPRT-Test.")],
    13: [("frag das bitte über das tool ab",
          "Abgefragt: Turnier und SPRT-Test laufen, eine EPD-Analyse nicht."),
         ("schau bitte nach statt zu raten",
          "Nachgesehen: es laufen ein Turnier und ein SPRT-Test.")],
    14: [("stoppe sprt bitte hart, sanft hat nicht gereicht",
          "Der SPRT-Test ist abrupt gestoppt. Es läuft nur noch das Turnier."),
         ("brich den sprt lauf sofort ab",
          "Abrupt gestoppt. Das Turnier läuft weiter.")],
    15: [("die epd datei passt jetzt", "Die EPD-Analyse läuft."),
         ("epd ist jetzt gültig, leg los", "Läuft.")],
    16: [("die epd analyse läuft immer noch nicht",
          "Stimmt. Sie läuft jetzt."),
         ("du hast epd nicht gestartet",
          "Richtig, das hatte ich versäumt. Die EPD-Analyse läuft jetzt.")],
    18: [("ja bitte starten", "Das Turnier ist gestartet."),
         ("ja, mach", "Läuft.")],
    19: [("brich das turnier sofort ab",
          "Das Turnier wurde abrupt beendet, alle laufenden Partien sofort abgebrochen."),
         ("stoppe das turnier hart",
          "Abrupt beendet -- die laufenden Partien wurden sofort abgebrochen.")],
    20: [("zeig mir den aktuellen stand", "Der aktuelle Stand steht im Chat."),
         ("wie steht es gerade?", "Die Ergebnisse sind als Tabelle im Chat.")],
    28: [("halte das turnier an",
          "Das Turnier wird angehalten: laufende Partien werden noch beendet, neue starten nicht."),
         ("beende das turnier bitte",
          "Es wird sanft angehalten -- begonnene Partien laufen noch aus.")],
    31: [("halte die epd analyse an",
          "Die EPD-Analyse wird angehalten: begonnene Stellungen werden noch fertig gerechnet."),
         ("stoppe epd",
          "Sanft gestoppt -- laufende Stellungen werden noch zu Ende analysiert.")],
    32: [("turnier starten bitte", "Das Turnier ist gestartet."),
         ("bitte das turnier anwerfen", "Läuft.")],
    33: [("stoppe bitte das turnier",
          "Das Turnier wird angehalten: laufende Partien werden noch beendet, neue starten nicht."),
         ("mach das turnier aus",
          "Wird sanft angehalten -- was läuft, wird noch fertig gespielt.")],
    37: [("geht auch hart, dann ist es sofort aus",
          "Abrupt beendet, alle laufenden Partien sofort abgebrochen."),
         ("dann eben abrupt",
          "Das Turnier wurde abrupt beendet.")],
    39: [("danke dir", "Gern."),
         ("super, danke", "Gerne.")],
    50: [("starte bitte einen sprt lauf", "Der SPRT-Test ist gestartet."),
         ("sprt bitte starten", "Läuft.")],
    55: [("stelle das turnier bitte auf 1000 partien in 100 runden",
          "Steht jetzt auf 10 Spiele pro Runde über 100 Runden, also 1000 pro Paarung."),
         ("ich will 1000 spiele verteilt auf 100 runden",
          "Eingestellt: 10 Spiele pro Runde, 100 Runden, macht 1000 pro Paarung.")],
    56: [("1000 partien in 100 runden, ohne vorher zu prüfen",
          "Steht jetzt auf 10 Spiele pro Runde über 100 Runden, also 1000 pro Paarung."),
         ("stell einfach 1000 spiele in 100 runden ein, keine checks",
          "Eingestellt: 10 pro Runde, 100 Runden, zusammen 1000 pro Paarung.")],
    73: [("nur antworten bitte, nichts ausführen. warum lief sprt nicht?",
          "Ich hatte gestoppt und die Zeitkontrolle gesetzt, den start-Aufruf aber ausgelassen."),
         ("bitte keine aktion, nur eine erklärung: warum wurde sprt nicht gestartet?",
          "Weil ich nach dem Stoppen kein start aufgerufen habe. Mein Fehler.")],
    74: [("das war keine technische hürde. sag mir kurz was wirklich war",
          "Stimmt, technisch war nichts. Ich habe den Startschritt schlicht ausgelassen."),
         ("erklär mir bitte ehrlich, warum sprt nicht lief",
          "Es gab keinen Hinderungsgrund. Ich habe schlicht nicht gestartet.")],
    75: [("was soll \"nicht initialisiert\" heißen? kurz bitte",
          "Nichts -- so einen Zustand gibt es nicht. Es fehlte einfach der start-Aufruf."),
         ("erklär mir den begriff \"initialisiert\", kurze antwort",
          "Der war von mir erfunden. Einen Initialisierungsschritt gibt es nicht.")],
    76: [("schließ bitte das programm", "Die Anwendung wird geschlossen."),
         ("ich bin fertig, mach zu", "Wird geschlossen.")],
    77: [("bitte turnier starten", "Das Turnier ist gestartet."),
         ("Starte das Turnier", "Läuft.")],
    81: [("was läuft denn alles gerade?",
          "Es laufen gleichzeitig ein Turnier, ein SPRT-Test und eine EPD-Analyse."),
         ("gib mir einen überblick was aktiv ist",
          "Aktiv sind ein klassisches Turnier, ein SPRT-Test und eine EPD-Analyse.")],
    82: [("halte turnier und sprt sanft an",
          "Beide werden sanft angehalten: laufende Partien werden noch beendet."),
         ("stoppe bitte turnier und sprt, aber sanft",
          "Turnier und SPRT-Test werden sanft angehalten, begonnene Partien laufen aus.")],
    83: [("zeig mir das ergebnis vom sprt", "Die SPRT-Ergebnisse stehen im Chat."),
         ("wie ist der sprt ausgegangen?", "Das SPRT-Ergebnis wird im Chat angezeigt.")],
    84: [("mach mit sprt weiter", "Der SPRT-Test läuft wieder."),
         ("sprt bitte fortsetzen", "Läuft wieder.")],
    101: [("bist du noch da?", "Ja, bin da. Die letzte Antwort war leer, sorry. Was brauchst du?"),
          ("hallo? antwortest du noch?", "Ich bin da -- da kam vorhin nichts, Entschuldigung.")],
    114: [("der dialog war doch längst zu, wieso schreibst du sowas?",
           "Zu Recht. Wenn ich antworte, ist der Dialog schon geschlossen -- das Tool gibt sein "
           "Ergebnis ja erst danach zurück. Ich hätte das Ergebnis melden müssen."),
          ("warum kündigst du einen dialog an, den du schon geschlossen weißt?",
           "Weil das falsch war. Das Tool liefert erst zurück, wenn du gewählt oder abgebrochen "
           "hast -- danach gibt es nichts mehr anzukündigen.")],
    115: [("wie muss ich es dir sagen, damit du es richtig machst?",
           "Gar nicht anders -- deine Formulierung war eindeutig. Der Fehler lag bei mir."),
          ("sag mir, was ich anders formulieren muss",
           "Nichts. Das Problem war nicht deine Anweisung, sondern dass ich einen längst "
           "geschlossenen Dialog als offen beschrieben habe.")],
    116: [("wie verhindere ich, dass du nochmal schreibst der dialog sei geöffnet?",
           "Dafür musst du nichts tun. Der Dialog ist immer schon zu, wenn ich zu Wort komme -- "
           "ich melde nur noch das Ergebnis."),
          ("ich will diesen satz nie wieder lesen. was muss ich tun?",
           "Nichts -- das liegt an mir. Ich beschreibe keine Dialoge mehr, nur noch deren "
           "Ausgang.")],
    117: [("und das passiert jetzt wirklich nicht mehr?",
           "Nein. Keine Dialog-Ankündigungen, nur noch das Ergebnis."),
          ("du sagst das also nie wieder?",
           "Nie wieder. Ich melde die gesetzte Datei oder den Abbruch, sonst nichts.")],
    126: [("was ist gerade am laufen?",
           "Ein klassisches Turnier und ein SPRT-Test. Keine EPD-Analyse."),
          ("läuft im moment was?",
           "Ja: ein Turnier und ein SPRT-Test.")],
    127: [("beende sprt bitte sanft",
           "Der SPRT-Test wird sanft angehalten, die laufende Partie wird noch beendet."),
          ("sprt bitte sauber runterfahren",
           "Wird sanft angehalten -- die begonnene Partie läuft noch aus.")],
    128: [("und jetzt, was läuft?",
           "Weiterhin ein Turnier und ein SPRT-Test, keine EPD-Analyse."),
          ("nochmal: was ist aktiv?",
           "Ein klassisches Turnier und ein SPRT-Test.")],
    131: [("was läuft denn jetzt?", "Es läuft ein klassisches Turnier."),
          ("ist noch was aktiv?", "Ja, das klassische Turnier läuft.")],
    133: [("was ist aktiv?", "Ein Turnier und ein SPRT-Test."),
          ("läuft was?", "Ja: Turnier und SPRT-Test.")],
    134: [("stoppe sprt bitte freundlich",
           "Der SPRT-Test wird sanft angehalten, die laufende Partie noch beendet. Das Turnier "
           "läuft weiter."),
          ("sprt bitte sanft beenden",
           "Wird sanft angehalten. Das Turnier bleibt davon unberührt.")],
    135: [("und jetzt?", "Jetzt läuft nur noch das klassische Turnier."),
          ("was ist übrig?", "Nur noch das Turnier.")],
    136: [("wie ist der epd lauf ausgegangen?",
           "Die EPD-Ergebnisse stehen als Tabelle im Chat."),
          ("zeig mir das epd ergebnis",
           "Das EPD-Ergebnis wird im Chat angezeigt.")],
    138: [("zeig mir bitte das ergebnis vom turnier",
           "Die Turnierergebnisse stehen als Tabelle im Chat."),
          ("wie ist das turnier ausgegangen?",
           "Das Turnierergebnis wird im Chat angezeigt.")],
    142: [("bitte turnier jetzt starten", "Das Turnier ist gestartet."),
          ("fang bitte mit dem turnier an", "Läuft.")],
    143: [("ja, leg los", "Das Turnier ist gestartet."),
          ("ja, fang an", "Läuft.")],
    144: [("das lief nicht, bitte wirklich starten",
           "Stimmt, es lief nicht. Jetzt läuft es."),
          ("du hast nichts gestartet, mach es bitte",
           "Richtig, da war nichts. Das Turnier läuft jetzt.")],
    145: [("nochmal: starte es", "Das Turnier ist gestartet."),
          ("bitte jetzt starten", "Läuft.")],
    146: [("start bitte", "Das Turnier ist gestartet."),
          ("jetzt aber wirklich starten", "Läuft jetzt.")],
    147: [("sag mir was läuft",
           "Es läuft ein klassisches Turnier, weiter nichts."),
          ("liste mir auf was aktiv ist",
           "Aktiv ist nur das klassische Turnier.")],
    148: [("bitte erst nachsehen, dann antworten",
           "Nachgesehen: es läuft nur das klassische Turnier."),
          ("frag das tool, bevor du antwortest",
           "Abgefragt -- aktiv ist ausschließlich das Turnier.")],
    150: [("ich will eine pgn datei aussuchen", None),
          ("lass mich eine partie zum anschauen wählen", None)],
}
